name: behavior_subject_example
description: "Example of authorization using BehaviorSubject."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mocktail: 1.0.4
  rxdart: 0.27.7
  test: 1.25.2


dev_dependencies:
  surf_lint_rules: 3.1.0

flutter:
  uses-material-design: true
